server:
  port: 10000

spring:
  application:
    name: 'mybatis-demo'
  datasource:
    username: dev_admin
    password: sidNkyy6h0wkNinH
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.83.128.1:13310/crm?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai

#mybatis:
#  config-location: ''
#  configuration:
#    map-underscore-to-camel-case: true
